#!/usr/bin/env ruby
# Ruby script for interfacing with mrender to produce volumetric
# visualizations

require 'optparse'
require 'open3'
require 'digest/sha1'

require File.join(File.expand_path(File.dirname(__FILE__)), "media-commands")

require 'rubygems'
require 'progressbar'

DEFAULT_RESOLUTION = [320, 240]
DEFAULT_NUM_THREADS = 16

# # copied in for now
# mrender_string += " -fr -0.1 0 4.1"
# mrender_string += " -dn -1"
# mrender_string += " -di 0"
# mrender_string += " -df 1"
# mrender_string += " -up 0 -1 0"
# mrender_string += " -rh"
# mrender_string += " -ar"
# mrender_string += " -ur -1 1"
# mrender_string += " -vr -1 1"
# mrender_string += " -step 0.0008"
# mrender_string += " -nt 16"
# mrender_string += " -k00 cubic:1,0"
# mrender_string += " -k11 cubicd:1,0"
MRENDER_DEFAULTS = {
  :eye_pos => "-0.1 0 4.1",
  :look_at => "0 0 0",
  :near_clip => "-1",
  :image_distance => "0",
  :far_clip => "1",
  :up => "0 -1 0",
  :right_handed => true,
  :at_relative => true,
  :u_range => "-1 1",
  :v_range => "-1 1",
  :step => "0.0008",
  :value_kernel => "cubic:1,0",
  :k1_kernel => "cubicd:1,0",
  :angle => "0",
}

# src/nrrd/enumsNrrd.c : _nrrdMeasureStr
valid_measures = [
  "min",
  "max",
  "mean",
  "median",
  "mode",
  "product",
  "sum",
  "L1",
  "L2",
  "Linf",
  "variance",
  "SD",
  "skew",
  "line-slope",
  "line-intercept",
  "line-error"
]

# src/gage/scl.c : _gageSclStrEqv
valid_queries = [
  "value", 
  "gradvec",
  "gradmag",
  "normal",
  "nperp", 
  "hessian",
  "laplacian",
  "hf",
  "heval",
  "heval0",
  "heval1",
  "heval2",
  "hevec",
  "hevec0",
  "hevec1",
  "hevec2",
  "2nddd",
  "geomten",
  "k1",
  "k2",
  "totalcurv",
  "st", # "shape trace",
  "si", # "shape index",
  "meancurv",
  "gausscurv",
  "curvdir1",
  "curvdir2",
  "flowlinecurv",
  "median"
]

mrender_bin = 'mrender'
filenames = []
@options = {
  :angle_range => (0..359),
  :angle_interval => 1,
  :output_resolution => DEFAULT_RESOLUTION,
  :show_frame_progress => false,
  :num_threads => DEFAULT_NUM_THREADS,
  :queries => ['val'],
  :measures => ['variance'],
  :cleanup => true
  # max
}

OptionParser.new do |opts|
  opts.summary_width = 30
  opts.banner = "Usage: #{File.basename(__FILE__)} [options] filename.nrrd"

  def opts.show_usage
    puts self
    exit
  end
  
  opts.on("-l","--[no-]leave",
          "Leave intermediate files") do |cleanup|
    @options[:cleanup] = !cleanup
  end
  
  opts.on("-nt THREADS","--num-threads=THREADS",
          "Number of threads for mrender (#{DEFAULT_NUM_THREADS})") do |threads|
    @options[:num_threads] = threads
  end
  
  opts.on("--is width,height", Array,
          "Output image/movie resolution (#{DEFAULT_RESOLUTION[0]},#{DEFAULT_RESOLUTION[1]})") do |resolution|
    @options[:output_resolution] = resolution
  end

  opts.on("--angles angle1,angle2", Array, 
          "Beginning and end angles for rendering (0,359)") do |angles|
    @options[:angle_range] = Range.new(angles[0],angles[1])
  end

  opts.on("-I INTERVAL","--interval=INTERVAL",
          "Interval at which to create projections") do |interval|
    @options[:angle_interval] = interval.to_i
  end
  
  opts.on("-C CAMERA_FILE","--camera_file=CAMERA_FILE",
          "Use camera file for mrender camera positions") do |camera_file|
    @options[:camera_file] = camera_file
  end
  
  opts.on("--measures m1,m2,...", Array,
          "Value measures to render, any of: #{valid_measures.join(', ')}") do |measures|
    @options[:measures] = measures & valid_measures
  end
  
  opts.on("--queries q1,q2,...", Array,
          "Value queries to render, any of: #{valid_queries.join(', ')}") do |queries|
    @options[:queries] = queries & valid_queries
  end

  opts.show_usage if ARGV.empty?

  begin
    opts.order(ARGV) do |filename|
      filenames << filename
    end
  rescue OptionParser::ParseError => e
    opts.warn e.message
    opts.show_usage
  end
end

def execute_mrender(command, max)
  if @options[:show_frame_progress]
    puts "\n"
    bar = ProgressBar.new("mrender", max)
  end
  Open3.popen3(command) do |stdin, stdout, stderr|
    if @options[:show_frame_progress]
      stderr.each(" ") do |element|
        if element =~ /(\d+)\/#{max.to_s}/
          bar.set($1.to_i)
        end
      end
    else
      stderr.readlines
    end
  end
  bar.finish unless !@options[:show_frame_progress]
end

def short_sha(input_object)
  # 7 characters is *usually* enough to avoid collision
  return Digest::SHA1.hexdigest(input_object.to_yaml)[0..6]
end

# @options parsed, run renderings
render_count = 0
@options[:queries].each do |query|
  @options[:measures].each do |measure|
    render_count += 1
    puts query + ", " + measure + " (" + render_count.to_s + "/" + 
      (@options[:queries].length*@options[:measures].length).to_s + ")"

    MRENDER_DEFAULTS[:output_resolution] = 
      @options[:output_resolution].join(' ')
    mrender_parameters = []
    if @options.has_key? :camera_file
      camera_file = YAML.load_file(@options[:camera_file])
      camera_file.each do |camera_params|
        # merge last parameters so we don't have to respecify each frame
        camera_params =  mrender_parameters.last.merge(camera_params) unless
          mrender_parameters.last.nil?
        # merge against defaults so custom params overwrite them
        mrender_parameters << MRENDER_DEFAULTS.merge(camera_params)
      end
    else
      @options[:angle_range].step(@options[:angle_interval]) do |angle|
        mrender_parameters << MRENDER_DEFAULTS.merge({:angle => angle})
      end
    end
    
    # puts mrender_parameters.to_yaml
    
    filename = filenames[0]
    output_video = sprintf("%s-%s-%s-%s.avi",
                     File.basename(filename, '.nrrd'), query, measure,
                      short_sha(mrender_parameters))
    
    if File.exists?(output_video)
      puts output_video + " exists, skipping"
      next
    end
    
    output_files = []
    
    render_bar = ProgressBar.new("volume render", mrender_parameters.length + 1)
    render_bar.set(0)
    render_bar.show_progress
    frame = 0
    
    mrender_parameters.each do |parameter|
      mrender_string = "#{mrender_bin} -i #{filenames[0]}"
      mrender_string += " -turn #{parameter[:angle]}"
      mrender_string += " -is #{parameter[:output_resolution]}"
      mrender_string += " -k scalar"
      mrender_string += " -q #{query}"
      mrender_string += " -m #{measure}"
      mrender_string += " -nt #{@options[:num_threads]}"
      
      # per-frame parameters
      mrender_string += " -fr #{parameter[:eye_pos]}"
      mrender_string += " -at #{parameter[:look_at]}"
      mrender_string += " -dn #{parameter[:near_clip]}"
      mrender_string += " -di #{parameter[:image_distance]}"
      mrender_string += " -df #{parameter[:far_clip]}"
      mrender_string += " -up #{parameter[:up]}"
      mrender_string += parameter[:right_handed] ? " -rh" : ''
      mrender_string += parameter[:at_relative] ? " -ar" : ''
      mrender_string += " -ur #{parameter[:u_range]}"
      mrender_string += " -vr #{parameter[:v_range]}"
      mrender_string += " -step #{parameter[:step]}"
      mrender_string += " -k00 #{parameter[:value_kernel]}"
      mrender_string += " -k11 #{parameter[:k1_kernel]}"
  
      output_file = File.basename(filename, '.nrrd') +
                    sprintf("-%s-%s-render-%s.nrrd",
                      query, measure, short_sha(parameter))
  
      mrender_string += " -o #{output_file}"
  
      # puts angle.to_s + ": " + mrender_string
      # Open3.popen3(mrender_string) { |stdin, stdout, stderr| stderr.readlines }
      if File.exists?(output_file)
        puts output_file + " exists, skipping"
      else
        execute_mrender(mrender_string, @options[:output_resolution][1])
      end
  
      output_files << output_file
      render_bar.inc
      frame += 1
    end
    render_bar.finish

    minmax_bar = ProgressBar.new("min/max calc", output_files.length)
    # compute min/max of output projections
    output_files.each do |input_nrrd|
      Open3.popen3("unu minmax #{input_nrrd}") do |stdin, stdout, stderr|
        stdout.each("\n") do |line|
          if line =~ /^min: (\d+\.?\d*)/
            this_min = $1.to_f
            @global_min ||= this_min
            @global_min = this_min < @global_min ? this_min : @global_min
          elsif line =~ /^max: (\d+\.?\d*)/
            this_max = $1.to_f
            @global_max ||= this_max
            @global_max = this_max > @global_max ? this_max : @global_max
          end
        end
      end
      minmax_bar.inc
    end
    minmax_bar.finish

    # puts "min: #{@global_min}"
    # puts "max: #{@global_max}"

    output_pngs = []
    quantize_bar = ProgressBar.new("quantizing", output_files.length)
    # quantize into png's
    output_files.each do |input_nrrd|
      output_png = File.basename(filename, '.nrrd') +
                    sprintf("-%s-%s-%03d.png",
                      query, measure, output_pngs.length)
      quantize_string = "unu quantize" +
                        " -b 8 -min #{@global_min} -max #{@global_max}" + 
                        " -i #{input_nrrd} -o #{output_png}"
      Open3.popen3(quantize_string) do |stdin, stdout, stderr|
        stdout.readlines
      end
      output_pngs << output_png
      quantize_bar.inc
    end
    quantize_bar.finish

    output_jpgs = []
    jpg_bar = ProgressBar.new("image conv", output_pngs.length)
    # convert to jpeg's
    output_pngs.each do |input_png|
      output_jpg = File.basename(input_png, '.png') + '.jpg'
      Open3.popen3("convert -quality 100 #{input_png} #{output_jpg}") do |stdin, stdout, stderr|
        stdout.readlines
      end
      output_jpgs << output_jpg
      jpg_bar.inc
    end
    jpg_bar.finish

    # convert to video
    mencoder_string = "mencoder #{output_jpgs.map{|i| 'mf://' + i}.join(' ')}" +
                      " -o #{output_video}" +
                      " -mf fps=10" +
                      " -ovc lavc -lavcopts vcodec=msmpeg4v2:vbitrate=800" +
                      " 2>&1"
    # puts mencoder_string
    safe_execute do
      execute_mencoder(mencoder_string)
    end
    
    puts "Output: " + output_video
    
    if @options[:cleanup]
      cleanup_files = []
      cleanup_files += output_jpgs + output_pngs + output_files
      cleanup_bar = ProgressBar.new("cleanup", cleanup_files.length)
      cleanup_files.each do |cleanup|
        File.unlink(cleanup)
        cleanup_bar.inc
      end
      cleanup_bar.finish
    end
  end
end
